const getStateWithKey = () => {
    return [
            {key:'in-py', name:"Puducherry"},
            {key:'in-ld', name:""},
            {key:'in-wb', name:""},
            {key:'in-or', name:""},
            {key:'in-br', name:"Bihar"},
            {key:'in-sk', name:""},
            {key:'in-ct', name:""},
            {key:'in-tn', name:"Tamil Nadu"},
            {key:'in-mp', name:"Madhya Pradesh"},
            {key:'in-2984', name:"Gujarath"},
            {key:'in-ga', name:""},
            {key:'in-nl', name:""},
            {key:'in-mn', name:"Manipur"},
            {key:'in-ar', name:""},
            {key:'in-mz', name:""},
            {key:'in-tr', name:""},
            {key:'in-3464', name:""},
            {key:'in-dl', name:"Delhi"},
            {key:'in-hr', name:"Haryana"},
            {key:'in-ch', name:""},
            {key:'in-hp', name:"Himachal Pradesh"},
            {key:'in-jk', name:""},
            {key:'in-kl', name:"Kerala"},
            {key:'in-ka', name:"Karnataka"},
            {key:'in-dn', name:""},
            {key:'in-mh', name:"Maharashtra"},
            {key:'in-as', name:"Assam"},
            {key:'in-ap', name:"Andhra Pradesh"},
            {key:'in-ml', name:""},
            {key:'in-pb', name:"Punjab"},
            {key:'in-rj', name:"Rajasthan"},
            {key:'in-up', name:""},
            {key:'in-ut', name:""},
            {key:'in-jh', name:""}
        ]
    }